---
- name: Prepare linux virt host
  gather_facts: no
  hosts: localhost
  tasks:
    - name: Include packages/services to install/set
      include_vars: main.yml

    - name: Install epel repository
      yum: name=epel-release state=present

    - name: Install IUS repository
      yum: name=https://centos7.iuscommunity.org/ius-release.rpm

    - block:
      - name: Install yum-utils
        yum: name=yum-utils state=present
      - name: Add Docker CE repo
        shell:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install packages
      yum: name={{ item }} state=present
      with_items: '{{ packages_to_install }}'

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start Libvirtd service
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Update pip
      pip:
        name: pip
        state: latest

    - name: Install virtualenv package
      pip:
        name: virtualenv
        state: present

    - name: Delete default KVM network
      virt_net:
        state: absent
        name: default

- import_playbook: nested-virt.yml
